niagara-objs := niagara_cpld.o niagara-i2c-algo-bit.o niagara-i2c-algo.o niagara-i2c-mux.o \
	niagara-i2c-ext-algo.o n818_cpld.o n820_cpld.o im8724_cpld.o im13233.o im13264.o im13262.o

obj-$(CONFIG_NIAGARA_PLATFORM) := niagara.o n840.o
