#ifndef _N821_CPLD_H__
#define _N821_CPLD_H__

/*
 * CPLD addresses.
 */
#define CPLD_ADDR_S_PAD			0x03
#define CPLD_ADDR_RST_CTL		0x04
#define CPLD_ADDR_MISC_CSR		0x05
#define CPLD_ADDR_MISC_STAT		0x06
#define CPLD_ADDR_FAN_CS		0x07
#define CPLD_ADDR_FAN_DC		0x08
#define CPLD_ADDR_AUX_CTL		0x0a
#define CPLD_ADDR_LTE_STAT		0x0b
#define CPLD_ADDR_WLAN_STAT		0x0c
#define CPLD_ADDR_LTE_WLAN_CTL		0x0d
#define CPLD_ADDR_INT_STAT		0x10
#define CPLD_ADDR_INT_EN		0x11
#define CPLD_ADDR_SYS_LED_CTL		0x12
#define CPLD_ADDR_PWR_LED_CTL		0x13
#define CPLD_ADDR_WLAN_LED_CTL		0x14


#define CPLD_ADDR_WAN_LED_CTL		0x15
#define CPLD_ADDR_LAN32_LED_CTL		0x16
#define CPLD_ADDR_LAN10_LED_CTL		0x17
#define CPLD_ADDR_P_CTL_0		0x18
#define CPLD_ADDR_P_CTL_1		0x19

#define CPLD_ADDR_TEST_0		0x20
#define CPLD_ADDR_TEST_1		0x21

#endif
