#!/bin/sh

source ./functions.sh

have_cavium_pci_device
require_good

OCTEON_REMOTE_DEBUG=1 oct-pci-csr ciu_fuse | grep -q BAR1
require_good

oct-pci-profile --dwell 1 --count=1 > $0.log
assert_good
assert grep -q "L2" $0.log
assert grep -q "DRAM ops count:" $0.log

$BOOTLOADER=`find_bootloader_for_pci_device`

if test "x$BOOTLOADER" != x ; then
  oct-pci-boot $BOOTLOADER
fi
