#!/bin/sh

source ./functions.sh

have_cavium_pci_device
require_good

OCTEON_REMOTE_DEBUG=1 oct-pci-csr ciu_fuse | grep -q BAR1
require_good

oct-pci-csr ciu_fuse | grep -q "CIU_FUSE"
assert_good

oct-pci-csr ciu_pp_rst | grep -q "RST0"
assert_good

