#!/bin/sh

source ./functions.sh

have_cavium_pci_device
require_good

OCTEON_REMOTE_DEBUG=1 oct-pci-csr ciu_fuse | grep -q BAR1
require_good

oct-pci-csr ciu_pp_rst | grep RST0 | grep -q 0x0
require_good

assert oct-pci-reset > /dev/null



