#!/bin/sh

source ./functions.sh

have_cavium_pci_device
require_good

OCTEON_REMOTE_DEBUG=1 oct-pci-csr ciu_fuse | grep -q BAR1
require_good

BOOTLOADER=`find_bootloader_for_pci_device`

if test "x$BOOTLOADER" != x; then 
   oct-pci-boot $BOOTLOADER > $0.log
   assert grep -q -F "Using bootloader image: $BOOTLOADER" $0.log
fi
